### ISSUE TITLE
Coursehunters site is redesign So its not working

### ISSUE THREAD

**Issue by sankalpgaikwad** [alekseylovchikov/ch-download#18]

**Comment by ShadyMohammed** [comment]
The error message is `TypeError: Cannot read property 'toString' of undefined`

**Comment by gokhantaskan** [comment]
```
Directory D:\CourseHunters\understanding-typescript created
File understanding-typescript\videos.txt created
TypeError: Cannot read property 'toString' of undefined

```

**Comment by sankalpgaikwad** [comment]
Its working thanx@Sawalhah

**Comment by PRASHANTPR7** [comment]
key @sankalpgaikwad mine is not working please help

**Comment by rapincx** [comment]
> key @sankalpgaikwad mine is not working please help

I worked patch, but I know how push to this repo

**Comment by jaeyholic** [comment]
Can't download paid courses with it. I have subscribed to premium and I want to download a course but I can't. I have entered my email and password but doesn't work.

**Comment by rapincx** [comment]
> Can't download paid courses with it. I have subscribed to premium and I want to download a course but I can't. I have entered my email and password but doesn't work.

I Fix this problem
But I don't push changes

**Comment by jaeyholic** [comment]
When will you push the changes?

**Comment by rapincx** [comment]
> When will you push the changes?

I don't push this repo because this repo not me

**Comment by jaeyholic** [comment]
Can I get it from your github then? If it's possible

**Comment by rapincx** [comment]
> Can I get it from your github then? If it's possible

 I think yes
After 5-10 min

**Comment by jaeyholic** [comment]
Thank you, let me know when you push it on your github so I can grab it

**Comment by rapincx** [comment]
> Thank you, let me know when you push it on your github so I can grab it

https://github.com/rapincx/ch-download/tree/chaos you can download from my branch
I create pull request to this repo
When author approve my pull, changes will be access

**Comment by rapincx** [comment]
#20

**Comment by alekseylovchikov** [comment]
it works now
