### ISSUE TITLE
Check your e-mail or password

### ISSUE THREAD

**Issue by Coolrunner86** [alekseylovchikov/ch-download#30]
Hi! The app refuses to work with valid credentials. Yesterday everything was fine. I'm able to log in on coursehunters with these credentials and see the course. Password doesn't contain any special symbols, tried to screen it with single quotes, got no success.

**Comment by KristinaTatur** [comment]
Hi! I have the same situation. It would be perfect if you can check and fix the issue. Thanks!

**Comment by KristinaTatur** [comment]
Ah, I see what happend here. I just need to replace URL 'coursehunters.net' with 'coursehunter.net'.

**Comment by anastely** [comment]
Same here !

**Comment by poterok** [comment]
Hi! I have the same situation.

**Comment by alekseylovchikov** [comment]
solved

**Comment by Coolrunner86** [comment]
Thanks!
