### ISSUE TITLE
CLI stopped downloading courses because CH changed slightly structure of the website

### ISSUE THREAD

**Issue by NazarB99** [alekseylovchikov/ch-download#39]

**Comment by NazarB99** [comment]
> getting this error.
> C:\Users\Sankalp\Desktop\coursehunters\ch-download\src\download\getVideos.js:26
> urlMaterials = videoMaterials[1].parent.attribs.href
> ^
> 
> TypeError: Cannot read property 'parent' of undefined
> at Request._callback (C:\Users\Sankalp\Desktop\coursehunters\ch-download\src\download\getVideos.js:26:44)
> at Request.self.callback (C:\Users\Sankalp\Desktop\coursehunters\ch-download\node_modules\request\request.js:185:22)
> at Request.emit (events.js:315:20)
> at Request. (C:\Users\Sankalp\Desktop\coursehunters\ch-download\node_modules\request\request.js:1154:10)
> at Request.emit (events.js:315:20)
> at IncomingMessage. (C:\Users\Sankalp\Desktop\coursehunters\ch-download\node_modules\request\request.js:1076:12)
> at Object.onceWrapper (events.js:421:28)
> at IncomingMessage.emit (events.js:327:22)
> at endReadableNT (_stream_readable.js:1218:12)
> at processTicksAndRejections (internal/process/task_queues.js:84:21)

it fixed now you can check it out

**Comment by sankalpgaikwad** [comment]
Thanks man its working now. Appreciate your efforts and time.

**Comment by jeykarlokes** [comment]
HI nazar,

the new branch is not working. download not starting

![image](https://user-images.githubusercontent.com/26407094/88618272-46e10a00-d0b6-11ea-997f-19180be8a4e7.png)

**Comment by silverbret1709** [comment]
Please fix new site structure

**Comment by OtchereDev** [comment]
if you still having issues with downloader, kindly check out this cool download i have built
https://github.com/OtchereDev/coursehunter-video-downloader
