### ISSUE TITLE
npm WARN parsecoursehunters@0.0.4 No repository field.

### ISSUE THREAD

**Issue by evmorov** [alekseylovchikov/ch-download#4]
Hey. I'm getting this error when trying

```
npm install
```

I'm using master fb292ff.

```
npm -v 5.3.0
osx
```

**Comment by theIYD** [comment]
@evmorov It's because the repository field is not defined in `package.json`. Don't worry, everything works fine. Thanks to @alekseylovchikov

**Comment by evmorov** [comment]
What should I do? Wait for a commit/fix or define something in `package.json`?

**Comment by theIYD** [comment]
You need not do anything. Just follow the procedure. Everything works as expected.

**Comment by theIYD** [comment]
Its a warning not a bug. Just follow the procedure. Do `node index -u <course-url>`. It will start normally.

**Comment by evmorov** [comment]
Oh. Got it. I'll try later and will close the issue. Thanks

**Comment by theIYD** [comment]
welcome :+1:
