### ISSUE TITLE
Unable to get premium

### ISSUE THREAD

**Issue by Densitty** [alekseylovchikov/ch-download#42]
Hi!

I have been trying to pay for premium access but could not. Could it be the merchants you guys use? I am a subscriber from West Africa.

Regards

**Comment by cooliofv** [comment]
Подтверждаю. Программа перестала скачивать премиум курсы
![Untitled](https://user-images.githubusercontent.com/19313777/87870653-ddc10e80-c9b2-11ea-8a14-8a6902f5e6c6.png)

**Comment by Densitty** [comment]
I have gotten it resolved. Thanks.19.07.2020, 09:28, "Aleksey" <notifications@github.com>:
Подтверждаю. Программа перестала скачивать премиум курсы

**Comment by NazarB99** [comment]
It has been fixed #40. I made PR but the owner of this repository not answering

**Comment by jeykarlokes** [comment]
> It has been fixed #40. I made PR but the owner of this repository not answering
> BTW you can install my fork and it will download premium courses
'hi nazar,
i used for the fork but not working can help me how to download the course from ch ? download not starting ?
