### ISSUE TITLE
Videos not downloading

### ISSUE THREAD

**Issue by siddhant1** [alekseylovchikov/ch-download#6]
I am having an issue where the downloader starts but says creating videos.txt and then stops and nothing is downloaded , a video.txt file of 0kb is created (blank)

**Comment by gebeto** [comment]
@siddhant1 please give me a link of course, maybe it's some prohibited symbols in video names

**Comment by siddhant1** [comment]
https://coursehunters.net/source/totalreact

Can you check this course

**Comment by gebeto** [comment]
Yeah, it is a **PAID** course, you can't download that

**Comment by siddhant1** [comment]
Okay thank you so much

**Comment by siddhant1** [comment]
Okay thank you so much
