### ISSUE TITLE
Получаю ошибку throw er; // Unhandled stream error in pipe.

### ISSUE THREAD

**Issue by wassalam01** [alekseylovchikov/ch-download#7]
`Start download video: Урок 12. Блок 2 HTML \ CSS - 2
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: ENOENT: no such file or directory, open 'D:\1\sozdanie-kontentnogo-sayta-na-jekyll-ot-a-do-ya\Урок 12. Блок 2 HTML \ CSS - 2.mp4'`

`coursehunters -u https://coursehunters.net/course/sozdanie-kontentnogo-sayta-na-jekyll-ot-a-do-ya -l 12`

**Comment by alekseylovchikov** [comment]
@wassalam01 привет! какая ось и версия ноды?

**Comment by wassalam01** [comment]
Спасибо что отозвались, привет! Win 10
`$ node -v
v8.9.4
`
Я думаю дело не в ноде, а в том что слеши в названии Урок 12. Блок 2 HTML \ CSS - 2, может что то типа решения в лоб - если есть слеши то тупо их заменять на что то другое.

**Comment by alekseylovchikov** [comment]
@wassalam01 поправим

**Comment by alekseylovchikov** [comment]
@wassalam01 коммитнул фикс, попробуй

**Comment by wassalam01** [comment]
@alekseylovchikov Да, все работает, по крайней мере то что у меня не работало ) Спасибо, очень выручает, внутренний пессимизм заставляет скачивать на всякий, в России живу.
